module.exports = [
  {
    itemCode: "FujiAppleSA",
    itemName: "Apple",
    availableStock: 100,
    sellingPrice: 2.0,
    purchasePrice: 1.0,
    imageURL: "https://icons8.com/icon/13304/apple",
    category: "Fruits",
    sold: 120,
  },
  {
    itemCode: "MandarinOrangeCN",
    itemName: "Orange",
    availableStock: 150,
    sellingPrice: 1.8,
    purchasePrice: 0.8,
    imageURL: "https://icons8.com/icon/57233/orange",
    category: "Fruits",
    sold: 80,
  },
  {
    itemCode: "BananaTH",
    itemName: "Banana",
    availableStock: 200,
    sellingPrice: 1.5,
    purchasePrice: 0.4,
    imageURL: "https://icons8.com/icon/18957/banana",
    category: "Fruits",
    sold: 130,
  },
  {
    itemCode: "PearJP",
    itemName: "Pear",
    availableStock: 250,
    sellingPrice: 2.3,
    purchasePrice: 1.1,
    imageURL: "https://icons8.com/icon/18957/banana",
    category: "Fruits",
    sold: 150,
  },
];
