module.exports = [
  {
    itemCode: "FujiAppleSA",
    itemName: "Apple",
    availableStock: 100,
    sellingPrice: 2.0,
    purchasePrice: 1.0,
    imageURL: "https://i.imgur.com/cTDTABm.png",
    category: "Fruits",
    sold: 120,
  },
  {
    itemCode: "MandarinOrangeCN",
    itemName: "Orange",
    availableStock: 150,
    sellingPrice: 1.8,
    purchasePrice: 0.8,
    imageURL: "https://i.imgur.com/lGGp9U3.png",
    category: "Fruits",
    sold: 80,
  },
  {
    itemCode: "BananaTH",
    itemName: "Banana",
    availableStock: 200,
    sellingPrice: 1.5,
    purchasePrice: 0.4,
    imageURL: "https://i.imgur.com/Dzv2ZSR.png",
    category: "Fruits",
    sold: 130,
  },
  {
    itemCode: "PearJP",
    itemName: "Pear",
    availableStock: 250,
    sellingPrice: 2.3,
    purchasePrice: 1.1,
    imageURL: "https://i.imgur.com/FIgennO.png",
    category: "Fruits",
    sold: 150,
  },
];
